//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap TabErrors {
            get {
                object obj = ResourceManager.GetObject("TabErrors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabOutput {
            get {
                object obj = ResourceManager.GetObject("TabOutput", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabWatch {
            get {
                object obj = ResourceManager.GetObject("TabWatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolBreakpoint {
            get {
                object obj = ResourceManager.GetObject("ToolBreakpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolClearBookmarks {
            get {
                object obj = ResourceManager.GetObject("ToolClearBookmarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolClearBreakpoints {
            get {
                object obj = ResourceManager.GetObject("ToolClearBreakpoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolCloseFile {
            get {
                object obj = ResourceManager.GetObject("ToolCloseFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolCommentLines {
            get {
                object obj = ResourceManager.GetObject("ToolCommentLines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolCopy {
            get {
                object obj = ResourceManager.GetObject("ToolCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolCut {
            get {
                object obj = ResourceManager.GetObject("ToolCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolDecreaseIndent {
            get {
                object obj = ResourceManager.GetObject("ToolDecreaseIndent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolDelete {
            get {
                object obj = ResourceManager.GetObject("ToolDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolErrors {
            get {
                object obj = ResourceManager.GetObject("ToolErrors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolExamples {
            get {
                object obj = ResourceManager.GetObject("ToolExamples", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolExistingItem {
            get {
                object obj = ResourceManager.GetObject("ToolExistingItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolFind {
            get {
                object obj = ResourceManager.GetObject("ToolFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolGoToLine {
            get {
                object obj = ResourceManager.GetObject("ToolGoToLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolHelp {
            get {
                object obj = ResourceManager.GetObject("ToolHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolIncreaseIndent {
            get {
                object obj = ResourceManager.GetObject("ToolIncreaseIndent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolLibrary {
            get {
                object obj = ResourceManager.GetObject("ToolLibrary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolNewFile {
            get {
                object obj = ResourceManager.GetObject("ToolNewFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolNewItem {
            get {
                object obj = ResourceManager.GetObject("ToolNewItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolNewProject {
            get {
                object obj = ResourceManager.GetObject("ToolNewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolOpenFile {
            get {
                object obj = ResourceManager.GetObject("ToolOpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolOptions {
            get {
                object obj = ResourceManager.GetObject("ToolOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolOutputPanel {
            get {
                object obj = ResourceManager.GetObject("ToolOutputPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolPaste {
            get {
                object obj = ResourceManager.GetObject("ToolPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolPause {
            get {
                object obj = ResourceManager.GetObject("ToolPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolProjectPanel {
            get {
                object obj = ResourceManager.GetObject("ToolProjectPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolRedo {
            get {
                object obj = ResourceManager.GetObject("ToolRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolRemove {
            get {
                object obj = ResourceManager.GetObject("ToolRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolReplace {
            get {
                object obj = ResourceManager.GetObject("ToolReplace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolRestart {
            get {
                object obj = ResourceManager.GetObject("ToolRestart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolRun {
            get {
                object obj = ResourceManager.GetObject("ToolRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolSave {
            get {
                object obj = ResourceManager.GetObject("ToolSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolSaveAll {
            get {
                object obj = ResourceManager.GetObject("ToolSaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolSnippets {
            get {
                object obj = ResourceManager.GetObject("ToolSnippets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolStepInto {
            get {
                object obj = ResourceManager.GetObject("ToolStepInto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolStepOut {
            get {
                object obj = ResourceManager.GetObject("ToolStepOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolStepOver {
            get {
                object obj = ResourceManager.GetObject("ToolStepOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolStop {
            get {
                object obj = ResourceManager.GetObject("ToolStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolToolsPanel {
            get {
                object obj = ResourceManager.GetObject("ToolToolsPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolUnCommentLines {
            get {
                object obj = ResourceManager.GetObject("ToolUnCommentLines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolUndo {
            get {
                object obj = ResourceManager.GetObject("ToolUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolWebRun {
            get {
                object obj = ResourceManager.GetObject("ToolWebRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeBatchFile {
            get {
                object obj = ResourceManager.GetObject("TreeBatchFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeCodeFile {
            get {
                object obj = ResourceManager.GetObject("TreeCodeFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeCodeFileDefault {
            get {
                object obj = ResourceManager.GetObject("TreeCodeFileDefault", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeExplore {
            get {
                object obj = ResourceManager.GetObject("TreeExplore", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeFolderFile {
            get {
                object obj = ResourceManager.GetObject("TreeFolderFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeHTMLFile {
            get {
                object obj = ResourceManager.GetObject("TreeHTMLFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeImageFile {
            get {
                object obj = ResourceManager.GetObject("TreeImageFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeJavaScript {
            get {
                object obj = ResourceManager.GetObject("TreeJavaScript", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeProjectFile {
            get {
                object obj = ResourceManager.GetObject("TreeProjectFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeScriptFile {
            get {
                object obj = ResourceManager.GetObject("TreeScriptFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeStyleFile {
            get {
                object obj = ResourceManager.GetObject("TreeStyleFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeTextFile {
            get {
                object obj = ResourceManager.GetObject("TreeTextFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeUnknownFile {
            get {
                object obj = ResourceManager.GetObject("TreeUnknownFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TreeXMLFile {
            get {
                object obj = ResourceManager.GetObject("TreeXMLFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
